language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 2.1.502
    - os: osx # OSX 10.11
      osx_image: xcode7.2
      dotnet: 2.1.502
branches:
  only:
  - master

before_script:
  dotnet restore

script:
  dotnet build
# script:
  # Run a new console app
  # - mkdir -p "test/test-dotnet-new" && pushd "test/test-dotnet-new"
  # - dotnet new
  # - dotnet restore
  # - dotnet --verbose run a b
  # - popd
